version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: catalobby
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: catalobby
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
    external: false